{% set version = "3.1.0.20240220" %}

package:
  name: types-openpyxl
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/t/types-openpyxl/types-openpyxl-{{ version }}.tar.gz
    sha256: 89d481e791c637e27ae6655c119e98fab2956126991d39f52da2dec93e17c1f9
  - url: https://raw.githubusercontent.com/python/typeshed/main/LICENSE
    sha256: 295f8538c94ae5c3043301cf7cff1c852dab6a786a8ddee471e061b40d5ecabe

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7

test:
  commands:
    - pip check
    - test -f $SP_DIR/openpyxl-stubs/__init__.pyi                 # [unix]
    - if not exist %SP_DIR%\\openpyxl-stubs\\__init__.pyi exit 1  # [win]
  requires:
    - pip

about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for openpyxl
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
    - conda-forge/mypy
